### ISSUE TITLE
Public API tightening

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#1066]
Following on from #1065

There's a few attributes that are set in `BaseClient.__init__` that look like contenders here for moving into the private API space. Here's what's remaining there...

- [x] `self.base_url` - Potentially modify this to a property setter / getter style, but not 100% obvious?
- [ ] `self.auth` - Potentially modify this to a property setter / getter style, but not 100% obvious? - _See #1185_
- [x] `self.timeout` - Looks like it should *definitely* move to a property getter / setter style, as per params/headers/cookies.
- [x] `self.max_redirects` - I think this one is okay as a public attribute, since it's just a plain int.
- [x] `self.trust_env` - Setting this after `__init__` isn't really valid (eg. the transport is already initialized) so we could move it to a read-only property? _See #1112_
- [x] `self.netrc` - Ought to be private. _See #1071_

**Comment by tomchristie** [comment]
Dropping the milestone on this from 0.14 to 1.0, since the remaining items here are pretty minor, but we should still track them.
