### ISSUE TITLE
Fix tests for Windows.

### ISSUE THREAD

**Issue by cansarigol** [encode/httpx#458]
- [x] Add Windows to the build matrix. (Closes by #457)
- [x] Skip tests that fail on Windows.(Closes by #402, Also Closes #191 )
- [ ] Remove lowercased environment variables test cases from the proxies tests. (Closes by #456 )

After complete these:

- [ ] Remove `os: windows` from `allow_failures` into `travis.yml`
- [ ] Fix `xfail`s for `AsyncioBackend` fails.

**Comment by tomchristie** [comment]
I'm not really sure what state the tests are in for windows at the moment.
Is anyone keen on digging into this? Really we oughta get them back on track, and then turn off "allowed failure" for them so we don't slip back into this.

**Comment by tomchristie** [comment]
We've recently added windows tests on the Uvicorn repo thanks to @euri10 - that'd be a good place to start when looking at how to add them here.
