### ISSUE TITLE
Version 0.11.0

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#724]
Checklist for our 0.11.0 release.

This one is a big deal, since it reintroduces the sync client, and is essentially a 1.0 pre-release in terms of how the API looks.

```python
>>> import httpx
>>> httpx.get('https://www.example.com')
<Response [200 OK]>
```

🎉✨ **TA-DA!** ✨🎉

I'd expect that we'll likely end up waiting for a period of time after this release, and then end up releasing a 1.0 with either no API changes, or only very minimal API changes. (The only remaining area I can see us still wanting to refine/change, would be some review making sure we've got an exception heirarchy/naming that we're entirely happy to stick with for 1.0 onwards)

- [x] Reintroduce `Client` as a sync client. #735
- [x] Reintroduce `WSGIDispatch`. #735
- [x] Top-level API becomes sync, not async. #735
- [x] Drop `Origin` from public API. #688
- [x] Use `httpx.Proxy()` for proxy configuration, not the `httpx.HTTPProxy` dispatch class. #713
- [ ] ~Consider switching `client.params`, `client.headers`, `client.cookies` so that they don't have a setter/getter mismatch.~ Refs #678 #274
- [ ] ~Consider dropping UDS support.~ #723
- [x] Wrap IO Exceptions in httpx exceptions. #707
- [x] Docs #727
- [x] `httpx.Auth` becomes public API. #732 #731

**Comment by florimondmanca** [comment]
I think the breaking in this release should not be underestimated from a user perspective. Granted, we’re still pre1.0, but a second abrupt round of breaking changes after 0.8 dropped sync might not be what we need.

So while I agree with basically reswitching from async to sync as the default, I’m thinking of ways we could help users migrate.

At the very least we could probably add a migration guide item to this checklist, as a prose-form and hand-guided tour of the change log, with hints on migrating a codebase that uses 0.10. Thoughts?

**Comment by tomchristie** [comment]
Things we could potentially could defer, pass-on, or mitigate: #678, #723, #713.

The big one is the sync API, which for our existing users means...

* Always use a client instance.
* Use the `httpx.AsyncClient()` naming.

If we're very clear about that, then I *think* the "okay we're done here API-wise" trade-off is probably worth it?

**Comment by florimondmanca** [comment]
Yes, those recommendations sound like okay proactive communication. Should we roll them out now, i.e. some time before 0.11 is out?

**Comment by StephenBrown2** [comment]
Still itching for `httpx`-native Retry functionality as a 1.0 API feature...

**Comment by tomchristie** [comment]
Sure, I could potentially see us including that.

Few things higher up on the priority list still atm, and wouldn’t *strictly* need to be a 1.0 feature (ie add more features/API post 1.0 is totally fine, the cutoff is for making sure any API we have introduced is in a final state.)

But yeah may not be a bad idea.

**Comment by iwoloschin** [comment]
A big +1 for built-in retry, though I've made a very simple and very silly recursive retry wrapper that appears to work reasonably well, other than polluting up your stack trace when something does go wrong.

**Comment by tomchristie** [comment]
Dropping #678, #723 since they're not really a hard requirement here.

**Comment by jayvdb** [comment]
Note 0.10.1 hasnt been tagged.
